CREATE TABLE microposts(
  id INT(11) NOT NULL AUTO_INCREMENT,
  content TEXT NOT NULL,
  user_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
